
server:
  port: 7001

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: dev
    password: dev
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8888
